#!/bin/bash

sudo mkdir /etc/ovpn/
# Creates directory for files, deprecated post first time use.
cd /etc/ovpn/
# Emter locatiom.
ls 
# List all files in location
sudo rm -f *.ovpn
# Remove all old files.S
ls
# List all files in location
read -p "Node deletion complete, check /etc/ovpn/"
# Pauses script to check if files are removed. Ignore this, temp testing.
cd /tmp/
# Moves to temp folder
sudo wget -p https://surfy-chinaz.com/dconfig/openvpn-config.zip
# Downloads new files to temp folder to avoid later conflicts and bloat in the system
sudo unzip surfy-chinaz.com/dconfig/openvpn-config.zip
# Unarchives config files
sudo mv *.ovpn /etc/ovpn/ 
# Moves files to intended location
#sudo sed -i '15s"^.*$"auth-user-pass /etc/openvpn/auth.conf"' *.ovpn
#Disabled by default, adds automatic authentication during configuration using the .conf file for usr and pw.


read -p "Update to /etc/ovpn/ complete. Press enter to exit"