#!/bin/bash
sudo mkdir /etc/ovpn/
# Creates directory for files, deprecated post first time use.
cd /etc/ovpn/
# Emter locatiom.
ls 
# List all files in location
sudo rm -f *.ovpn
# Remove all old files.S
ls
# List all files in location
read -p "Node deletion complete, check /etc/ovpn/"
# Pauses script to check if files are removed. Ignore this, temp testing.
cd /tmp/
# Moves to temp folder
sudo wget -p https://surfy-chinaz.com/dconfig/openvpn-config.zip
# Downloads new files to temp folder to avoid later conflicts and bloat in the system
sudo unzip surfy-chinaz.com/dconfig/openvpn-config.zip
# Unarchives config files
sudo mv *.ovpn /etc/ovpn/ 
# Moves files to intended location
cd /etc/ovpn/ 
# Enters intended file directory
ls 
# Lists all new files
read -p "Update complete. Press enter to continue"